version: '3.6'
services:
  iris:
    build: 
      context: .
      dockerfile: Dockerfile
    restart: always
    ports: 
      - 1972
      - 52785:52773
      - 53773
    volumes:
      - ./:/irisdev/app
    command:
      --check-caps false
    secrets:
      - gmail_cred
      - gmail_client_secret

secrets:
  gmail_cred:
    file: ./gmail_cred.json
  gmail_client_secret:
    file: ./gmail_client_secret.json